version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: gunicorn app.main:app --bind 0.0.0.0:8000 --worker-class
      uvicorn.workers.UvicornWorker
    ports:
      - 8000:8000
